# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
eval "$(pyenv init --path)"
eval "$(pyenv init --path)"
eval "$(oh-my-posh --init --shell bash --config ~/.mytheme.omp.json)"
eval "$(oh-my-posh --init --shell bash --config ~/.mytheme.omp.json)"
