code --install-extension batisteo.vscode-django
code --install-extension bigonesystems.django
code --install-extension mhutchie.git-graph
code --install-extension knisterpeter.vscode-github
code --install-extension github.vscode-pull-request-github
code --install-extension eamodio.gitlens
code --install-extension ms-python.gather
code --install-extension ms-toolsai.jupyter
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.python
code --install-extension ahmadawais.shades-of-purple
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension coenraads.bracket-pair-colorizer-2
code --install-extension alexdima.copy-relative-path
code --install-extension alefragnani.bookmarks
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.vs-keybindings
code --install-extension skyapps.fish-vscode
code --install-extension skyapps.fish-vscode
code --install-extension njpwerner.autodocstring
code --install-extension visualstudioexptteam.vscodeintellicode